import { useRouter } from 'next/router'
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import Head from 'next/head'
import Layout from '../components/Layout.js'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'

export default function Contact() {
  const router = useRouter()
  const supabaseClient = useSupabaseClient()
  const user = useUser()
  if(user){
    // Redirect to `/profile`
  }
  return (
    <Layout>
      <Head>
        <title>WebTech - user signin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* insert the Auth component, add the ThemeSupa as well */}
    </Layout>
  )
}
